'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { BrokerRelayBrand } from '@/components/BrokerRelayBrand'
import '@/components/billing.css'
import '@/components/workspace-guidance.css'
type Snapshot={checked_at:string;total:number;counts:Record<string,number>;issues:{category:string;reference:string;organisation_id:string;company:string;task:string;state:string;at_time:string;guidance:string}[];automation:{email_enabled:boolean;debit_enabled:boolean}|null;billing_jobs:{name:string;enabled:boolean}[]}
export default function OperationsPage(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all')
 async function load(){setBusy(true);setError('');try{const r=await supabase.rpc('platform_operations');if(r.error)throw r.error;setData(r.data)}catch(e){setData(null);setError((e as {message?:string}).message||'Operations could not be checked.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 return <main className="platformShell operationsPage"><header className="platformHeader"><BrokerRelayBrand compact/><Link className="billingHeaderLink" href="/platform/companies">Platform companies</Link></header><div className="platformBody"><nav className="platformSidebar" aria-label="Platform navigation"><Link href="/platform/companies">▦ Companies</Link><Link href="/platform/companies#invitations">✉ Invitations</Link><Link href="/platform/billing">▤ Billing &amp; plans</Link><Link className="platformNavActive" aria-current="page" href="/platform/operations">◉ Operations</Link><div className="platformSidebarBottom"><Link href="/dashboard">⌂ Broker Desk</Link></div></nav><div className="platformMain"><div className="platformHeading"><div><h1>Operations</h1><p>Review delivery failures, overdue work and temporary document cleanup.</p></div><button disabled={busy} onClick={()=>void load()}>{busy?'Checking…':'Refresh checks'}</button></div>{error&&<p className="notice error" role="alert">{error} Apply the operations SQL update if this function is unavailable. Access is restricted to the Platform Owner.</p>}
 {data&&<><p className="muted">Checked {new Date(data.checked_at).toLocaleString('en-AU')}. Overdue means more than one hour past the scheduled time.</p><div className="billingPlanGrid">{['billing','documents','followups','storage'].map(k=><section className="card" key={k}><h2>{({billing:'Billing delivery',documents:'Document relay',followups:'Loan follow-ups',storage:'Temporary uploads'} as Record<string,string>)[k]}</h2><strong>{data.counts[k]??0}</strong><p>Items requiring attention</p></section>)}</div><section className="card billingPanel"><h2>Billing configuration</h2><p>Invoice email: {data.automation?.email_enabled?'Enabled':'Disabled'} · Automatic debit: {data.automation?.debit_enabled?'Enabled':'Disabled'}</p>{data.billing_jobs.length?data.billing_jobs.map(j=><p key={j.name}>{j.name}: {j.enabled?'Scheduled':'Paused'}</p>):<p>No billing schedules found.</p>}<p className="muted">These checks show database configuration. They do not verify Stripe connectivity, email delivery, function deployment or successful scheduled execution.</p><Link className="billingHeaderLink" href="/platform/billing">Open billing configuration →</Link></section><section className="card billingPanel"><h2>Attention queue</h2><label>Show category<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All categories</option>{['billing','documents','followups','storage'].map(k=><option key={k}>{k}</option>)}</select></label><p>{data.total} items in total. Showing the oldest {data.issues.length}; refresh after resolving issues.</p>{data.total===0&&<p>No items currently meet these failure or overdue checks. Complete the pilot delivery tests before treating the platform as ready.</p>}<div className="tableWrap"><table><thead><tr><th>Company / task</th><th>Status / time</th><th>Next action</th></tr></thead><tbody>{data.issues.filter(i=>filter==='all'||i.category===filter).map(i=><tr key={i.category+i.reference}><td><Link href={'/platform/companies/'+i.organisation_id}>{i.company}</Link><p>{i.category}: {i.task}</p><small>Reference: {i.reference}</small></td><td>{i.state}<p>{new Date(i.at_time).toLocaleString('en-AU')}</p></td><td>{i.guidance}{i.category==='billing'&&<p><Link href={'/platform/billing?company='+i.organisation_id}>Review company billing →</Link></p>}</td></tr>)}</tbody></table></div></section></>}
 </div></div></main>
}
