// @ts-ignore Deno resolves the pinned remote dependency.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.95.0'
export function required(name: string) { const value = Deno.env.get(name); if (!value) throw new Error(`MISSING_${name}`); return value }
export function adminClient() { return createClient(required('SUPABASE_URL'), required('SUPABASE_SERVICE_ROLE_KEY'), { auth: { persistSession: false } }) }
export function cors(req: Request) { const origin = req.headers.get('origin') ?? ''; const allowed = (Deno.env.get('BILLING_ALLOWED_ORIGINS') ?? '').split(',').map(x => x.trim()); return { 'Access-Control-Allow-Origin': allowed.includes(origin) ? origin : 'null', 'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Vary': 'Origin' } }
export function json(data: unknown, status = 200, headers: Record<string,string> = {}) { return new Response(JSON.stringify(data), { status, headers: { ...headers, 'Content-Type': 'application/json' } }) }
export async function checked(result: PromiseLike<any>) { const r = await result; if (r.error) throw new Error('BILLING_DATABASE_ERROR'); return r.data }
export async function stripe(path: string, fields?: Record<string,string>, key?: string) {
 const response = await fetch(`https://api.stripe.com/v1/${path}`, { method: fields ? 'POST' : 'GET', headers: { Authorization: `Bearer ${required('STRIPE_SECRET_KEY')}`, 'Stripe-Version': '2024-06-20', ...(fields ? { 'Content-Type': 'application/x-www-form-urlencoded' } : {}), ...(key ? { 'Idempotency-Key': key } : {}) }, body: fields ? new URLSearchParams(fields) : undefined, signal: AbortSignal.timeout(20000) })
 const data = await response.json(); if (!response.ok) throw new Error(`STRIPE_${String(data.error?.code ?? response.status).toUpperCase().replace(/[^A-Z0-9_]/g,'_')}`); return data
}
export const escapeHTML = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export const amount = (n: number) => new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100)
export const date = (value: string) => new Date(value).toLocaleDateString('en-AU',{timeZone:'Australia/Melbourne'})
export function invoiceEmail(i: any, kind: string, url: string) {
 const number = `BR-${String(i.invoice_number).padStart(6,'0')}`; const receipt = kind === 'receipt_email'; const failure = kind === 'failure_email'
 const title = receipt ? `Payment receipt ${number}` : failure ? `Payment needs attention ${number}` : `Tax invoice ${number}`
 const scheduled = i.debit_at ? date(i.debit_at) : date(`${i.due_date}T12:00:00Z`)
 const intro = receipt ? `Payment of ${amount(i.total_cents)} has been received. Reference: ${i.payment_reference || ''}.` : failure ? 'Automatic collection was unsuccessful. Please contact the Platform Owner to arrange payment. This is not a receipt.' : i.status==='paid' ? 'This invoice has been paid. A payment receipt will be sent separately.' : `Your invoice for ${i.month.slice(0,7)} is ready. ${i.automatic_collection ? `Your authorised bank account ending ${i.bank_last4 || '••••'} will be debited ${amount(i.total_cents)} on ${scheduled}. Mandate reference: ${i.mandate_ref}.` : `Payment is due ${scheduled}. Please follow the payment instructions below; automatic collection is not authorised for this invoice.`} You will receive a receipt after payment succeeds.`
 const lines = i.lines.map((l: any) => `<tr><td>${escapeHTML(l.description)}</td><td>${l.quantity}</td><td>${amount(l.unit_cents)}</td><td>${amount(l.total_cents)}</td></tr>`).join('')
 const records = (i.settlement_records ?? []).map((r: any) => `<tr><td>${escapeHTML(r.application_number || 'Unavailable')}</td><td>${escapeHTML(r.broker_name)}</td><td>${escapeHTML(r.settlement_date || '')}</td><td>${r.included ? 'Included' : amount(r.charge_cents)+' + GST'}</td></tr>`).join('')
 const text = `${title}\n${intro}\n${i.supplier_snapshot.name} ABN ${i.supplier_snapshot.abn || ''}\nBill to: ${i.company_snapshot.legal_name || i.company_snapshot.name}\nSubtotal: ${amount(i.subtotal_cents)}\nGST: ${amount(i.gst_cents)}\nTotal: ${amount(i.total_cents)}\n${(i.settlement_records??[]).map((r:any)=>`${r.application_number} | ${r.broker_name} | ${r.settlement_date || ''}`).join('\n')}\n${url}/billing\n${i.supplier_snapshot.payment_instructions || ''}`
 const html = `<div style="font-family:Arial,sans-serif;color:#182b4d;max-width:760px;margin:auto"><h1 style="color:#12366c">BrokerRelay</h1><h2>${escapeHTML(title)}</h2><p>${escapeHTML(intro)}</p><p><strong>${escapeHTML(i.supplier_snapshot.name)}</strong><br>ABN ${escapeHTML(i.supplier_snapshot.abn)}<br>${escapeHTML(i.supplier_snapshot.address)}</p><p>Bill to: ${escapeHTML(i.company_snapshot.legal_name || i.company_snapshot.name)}<br>Invoice date: ${date(i.issued_at)}${receipt && i.paid_at ? `<br>Payment received: ${date(i.paid_at)}` : ''}</p><table style="width:100%;text-align:left" cellpadding="8"><tr><th>Description</th><th>Qty</th><th>Price ex GST</th><th>Amount ex GST</th></tr>${lines}</table><p>Subtotal: ${amount(i.subtotal_cents)}<br>GST (${i.gst_rate}%): ${amount(i.gst_cents)}<br><strong>Total: ${amount(i.total_cents)} including GST</strong></p>${records ? `<h3>Settlement records</h3><p>Broker shown is the broker who recorded settlement.</p><table style="width:100%;text-align:left" cellpadding="8"><tr><th>Application number</th><th>Broker</th><th>Settlement date</th><th>Usage charge</th></tr>${records}</table>` : '<p>No billable settlements in this month.</p>'}<p style="white-space:pre-wrap">${escapeHTML(i.supplier_snapshot.payment_instructions)}</p><p><a href="${escapeHTML(url)}/billing">View invoice in Company billing &amp; invoices</a></p><p><a href="https://aidez.com.au">Powered by BrokerRelay</a></p></div>`
 return { subject: title, text, html }
}
export async function verifyStripeSignature(raw: string, header: string, secret: string, now = Date.now()) {
 const parts = header.split(',').map(x=>x.split('=')); const t = parts.find(x=>x[0]==='t')?.[1]; const signatures = parts.filter(x=>x[0]==='v1').map(x=>x[1]);
 if (!t || !/^\d+$/.test(t) || Math.abs(now/1000-Number(t))>300) return false
 const key = await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify'])
 for (const s of signatures) { if (!/^[0-9a-f]{64}$/i.test(s)) continue; const bytes = Uint8Array.from(s.match(/../g)!,x=>parseInt(x,16)); if (await crypto.subtle.verify('HMAC',key,bytes,new TextEncoder().encode(`${t}.${raw}`))) return true }
 return false
}
