'use client'
import { BillingInvoice, money, monthLabel } from '@/lib/billing'
export function BillingInvoiceView({ invoice, preview = false }: { invoice: BillingInvoice; preview?: boolean }) {
 const taxed = (invoice.gst_rate ?? 0) > 0
 return <article className="billingInvoice" aria-label={preview ? 'Invoice preview' : `Invoice BR-${invoice.invoice_number}`}>
  <div className="billingInvoiceHeading"><div><h2>{preview ? 'Invoice preview' : `${taxed ? 'Tax invoice' : 'Invoice'} BR-${String(invoice.invoice_number).padStart(6, '0')}`} </h2><p>{monthLabel(invoice.month)} · {preview ? 'Estimate · not issued' : invoice.status === 'paid' ? 'Paid' : 'Payment due'}</p></div><button type="button" className="secondary billingNoPrint" onClick={() => window.print()}>Print / save PDF</button></div>
  <div className="billingColumns"><div><strong>{invoice.supplier_snapshot.name}</strong><p>{invoice.supplier_snapshot.address}</p>{invoice.supplier_snapshot.abn && <p>ABN {invoice.supplier_snapshot.abn}</p>}</div><div><strong>Bill to: {invoice.company_snapshot.legal_name || invoice.company_snapshot.name}</strong><p>{invoice.company_snapshot.billing_email}</p>{invoice.company_snapshot.abn && <p>ABN {invoice.company_snapshot.abn}</p>}</div></div>
  {preview ? <p className="notice">Preview only. No invoice has been issued and no payment is requested. Charges may change before the month closes.</p> : <p>Issued {new Date(invoice.issued_at).toLocaleDateString('en-AU')} · Due {new Date(`${invoice.due_date}T12:00:00Z`).toLocaleDateString('en-AU')}</p>}
  <div className="tableWrap"><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit price (ex GST)</th><th>Amount (ex GST)</th></tr></thead><tbody>{invoice.lines.map((line, i) => <tr key={i}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.unit_cents)}</td><td>{money(line.total_cents)}</td></tr>)}</tbody></table></div>
  {taxed && <div className="billingTotalBreakdown"><p>Subtotal (ex GST): {money(invoice.subtotal_cents ?? 0)}</p><p>GST ({invoice.gst_rate}%): {money(invoice.gst_cents ?? 0)}</p></div>}
  {!!invoice.settlement_records?.length && <><h3>Settlement records</h3><p className="muted">Broker shown is the broker who recorded settlement.</p><div className="tableWrap"><table><thead><tr><th>Application number</th><th>Broker</th><th>Settlement date</th><th>Allowance / usage</th></tr></thead><tbody>{invoice.settlement_records.map((record,i)=><tr key={i}><td>{record.application_number || 'Unavailable'}</td><td>{record.broker_name}</td><td>{record.settlement_date ? new Date(`${record.settlement_date}T12:00:00Z`).toLocaleDateString('en-AU') : 'Not recorded'}</td><td>{record.included ? 'Included in package' : `${money(record.charge_cents)} + GST`}</td></tr>)}</tbody></table></div></>}
  {!preview && invoice.automation_managed && <div className="billingStats"><div><small>Invoice email</small><span>{invoice.invoice_email_sent_at ? `Sent ${new Date(invoice.invoice_email_sent_at).toLocaleDateString('en-AU')}` : 'Awaiting email'}</span></div><div><small>Automatic collection</small><span>{invoice.status === 'paid' ? 'Paid' : (invoice.payment_status || 'Pending').replaceAll('_',' ')}</span>{invoice.debit_at && <span>Scheduled {new Date(invoice.debit_at).toLocaleDateString('en-AU',{timeZone:'Australia/Melbourne'})}</span>}</div><div><small>Receipt email</small><span>{invoice.receipt_email_sent_at ? `Sent ${new Date(invoice.receipt_email_sent_at).toLocaleDateString('en-AU')}` : invoice.status === 'paid' ? 'Awaiting receipt' : 'After payment succeeds'}</span></div></div>}
  {!preview && invoice.delivery_error && <p className="notice error">Billing delivery needs attention: {invoice.delivery_error.replaceAll('_',' ').toLowerCase()}. Contact the Platform Owner.</p>}
  <p className="billingTotal">{preview ? 'Estimated total' : 'Total'} AUD {money(invoice.total_cents)}{taxed && ' (incl GST)'}</p>
  {invoice.supplier_snapshot.payment_instructions && <p style={{ whiteSpace: 'pre-wrap' }}>{invoice.supplier_snapshot.payment_instructions}</p>}
  {invoice.payment_reference && <p>Payment reference: {invoice.payment_reference}</p>}
 </article>
}
