'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
export function BillingAutomationControls() {
 const [email,setEmail]=useState(false),[debit,setDebit]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{void(async()=>{const r=await supabase.from('billing_automation_settings').select('*').eq('id',true).single();if(r.error){setMessage('Apply the billing automation SQL update to configure this section.');return}setEmail(r.data.email_enabled);setDebit(r.data.debit_enabled);setLoaded(true)})()},[])
 async function save(){if(!window.confirm('Save billing automation settings? Ensure the worker, email sender and Stripe live connection are configured before enabling collection.'))return;setBusy(true);const r=await supabase.rpc('billing_set_automation',{p_email:email,p_debit:debit});setMessage(r.error?r.error.message:'Automation settings saved. These settings apply to new invoices and queued delivery jobs.');setBusy(false)}
 return <section className="card billingPanel"><h2>Monthly billing automation</h2><p className="muted">Invoice on the 1st, collection seven days after notice, receipt after successful payment. Configure Edge Functions and their secrets before enabling delivery. Previous invoices are not automatically emailed or debited.</p><div className="billingForm"><label className="check"><input type="checkbox" checked={email} disabled={!loaded||busy} onChange={e=>{setEmail(e.target.checked);if(!e.target.checked)setDebit(false)}}/>Email new invoices and payment receipts</label><label className="check"><input type="checkbox" checked={debit} disabled={!loaded||busy||!email} onChange={e=>setDebit(e.target.checked)}/>Collect authorised direct debits automatically</label><button type="button" disabled={!loaded||busy} onClick={()=>void save()}>Save automation settings</button>{message&&<p role="status" className="notice">{message}</p>}</div></section>
}
