'use client'
import { useEffect,useState } from 'react'
import { supabase } from '@/lib/supabase'
import '@/components/billing.css'
export type Performance={organisation_id:string;month?:string;settled_month?:number;missing_settlement_date?:number;clients:number;client_statuses:Record<string,number>;applications:number;application_statuses:Record<string,number>}
export function CompanyPerformance({companyId,head}:{companyId:string;head:boolean}){
 const [period,setPeriod]=useState('all')
 const [data,setData]=useState<Performance|null>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;setData(null);setError('');void(async()=>{const r=await supabase.rpc(period==='month'?(head?'company_performance_month':'my_portfolio_month'):(head?'company_performance':'my_portfolio_performance'),{p_org:companyId});if(!active)return;if(r.error){setError('Performance could not load. Ask the administrator to check the company performance SQL update.');return}setData(head?(r.data?.[0]??null):r.data)})();return()=>{active=false}},[companyId,head,period])
 return <section className="card billingPanel"><h2>{head?'Company performance':'Your accessible client portfolio'}</h2><div className="row" role="group" aria-label="Performance period"><button className={period==='all'?'':'secondary'} type="button" aria-pressed={period==='all'} onClick={()=>setPeriod('all')}>All time</button><button className={period==='month'?'':'secondary'} type="button" aria-pressed={period==='month'} onClick={()=>setPeriod('month')}>This month</button></div><p className="muted">{period==='month'?'New client records, new applications and loans with a settlement date this Melbourne calendar month.':'All-time records by current status.'} These counts are separate from monthly billable settlements.</p>{error&&<p role="alert">{error}</p>}{data&&<><div className="billingStats"><div><small>{period==='month'?'New clients':'Clients'}</small><strong>{data.clients}</strong></div><div><small>{period==='month'?'New applications':'Applications'}</small><strong>{data.applications}</strong></div>{period==='all'&&<div><small>In progress</small><strong>{data.applications-(data.application_statuses.settled??0)-(data.application_statuses.withdrawn??0)}</strong></div>}<div><small>{period==='month'?'Settlements this month':'Settled'}</small><strong>{period==='month'?(data.settled_month??0):(data.application_statuses.settled??0)}</strong></div></div>{period==='month' && <p className="muted">Reporting month: {data.month}. Settled loans without a settlement date: {data.missing_settlement_date??0} (excluded from monthly settlements). Older applications settled this month are included.</p>}{period==='all'&&<details><summary>View status breakdown</summary><h3>Clients</h3><p>{Object.entries(data.client_statuses).map(([k,v])=>k+': '+v).join(' · ')||'No clients yet'}</p><h3>Applications</h3><p>{Object.entries(data.application_statuses).map(([k,v])=>k.replaceAll('_',' ')+': '+v).join(' · ')||'No applications yet'}</p></details>}</>}{!data&&!error&&<p>Loading performance…</p>}</section>
}
