'use client'
import Link from 'next/link'
import '@/components/workspace-guidance.css'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
type Client={id:string;first_name:string;last_name:string}
export function WorkspaceGuidance({companyId,head,clients,unread}:{companyId:string;head:boolean;clients:Client[];unread:Record<string,number>}){
 const [counts,setCounts]=useState<{documents:number;applications:number}|null>(null),[setup,setSetup]=useState<{billing_email:string|null;logo_url:string|null}|null>(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;void(async()=>{const results=await Promise.all([supabase.from('document_requests').select('id',{count:'exact',head:true}).eq('organisation_id',companyId).in('status',['requested','failed']),supabase.from('loan_applications').select('id',{count:'exact',head:true}).eq('organisation_id',companyId).not('status','in','(settled,withdrawn)'),...(head?[supabase.from('organisations').select('billing_email,logo_url').eq('id',companyId).single()]:[])]);if(!active)return;const failed=results.find(r=>r.error);if(failed){setError('Some workspace checks could not load. Open the relevant page to review your work.');return}setCounts({documents:results[0].count??0,applications:results[1].count??0});if(head)setSetup(results[2].data as unknown as {billing_email:string|null;logo_url:string|null})})();return()=>{active=false}},[companyId,head])
 const waiting=clients.filter(c=>(unread[c.id]??0)>0)
 return <section className="card workspaceGuidance"><h2>Your next actions</h2>{error&&<p role="status">{error}</p>}<div className="workspaceActionGrid"><Link href="/messages">Unread conversations: {waiting.length}</Link><Link href="/documents">Open document requests: {counts?.documents??'Checking…'}</Link><Link href="/applications">Applications in progress: {counts?.applications??'Checking…'}</Link></div>{waiting.length>0&&<ul>{waiting.slice(0,5).map(c=><li key={c.id}><Link href={'/messages/'+c.id}>{c.first_name} {c.last_name}</Link> · {unread[c.id]} unread</li>)}</ul>}<p className="muted">Document requests include requests awaiting upload and failed deliveries. Applications in progress are a worklist, not an overdue warning.</p>{head&&<details><summary>Company setup checklist</summary><ul><li><Link href="/admin">Company details and billing email</Link> — {setup?(setup.billing_email?'Billing email recorded':'Add a billing email'):'Checking…'}</li><li><Link href="/admin">Company logo</Link> — {setup?(setup.logo_url?'Uploaded':'Optional: add your logo'):'Checking…'}</li><li><Link href="/admin/document-delivery">Verify document delivery and test a real upload</Link></li><li><Link href="/settings/mobile-appearance">Review mobile colours and text contrast</Link></li><li><Link href="/settings/follow-up-templates">Review default messages and custom greetings</Link></li><li><Link href="/billing">Confirm package, invoices and payment arrangements</Link></li><li><Link href="/admin">Invite additional staff if needed</Link></li></ul><p>Before inviting clients, test login, password reset and document delivery with a test account.</p></details>}</section>
}
