'use client'
import { BillingAutomationControls } from '@/components/BillingAutomationControls'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { BrokerRelayBrand } from '@/components/BrokerRelayBrand'
import { CompanyBillingPanel } from '@/components/CompanyBillingPanel'
import { BillingPlan, cents, monthStart, money } from '@/lib/billing'
import '@/components/billing.css'
type Settings = { setup_cents: number | null; broker_cents: number | null; supplier_name: string; supplier_abn: string; supplier_address: string; payment_instructions: string; grace_days: number }
export default function PlatformBillingPage() {
 const [ready,setReady]=useState(false), [plans,setPlans]=useState<BillingPlan[]>([]), [settings,setSettings]=useState<Settings|null>(null)
 const [companies,setCompanies]=useState<{id:string;name:string}[]>([]), [company,setCompany]=useState(''), [error,setError]=useState(''), [notice,setNotice]=useState(''), [busy,setBusy]=useState(false)
 async function load() {
  const [p,s,o]=await Promise.all([supabase.from('billing_plan_versions').select('*').order('effective_from',{ascending:false}),supabase.from('billing_settings').select('*').single(),supabase.rpc('platform_company_contact_overview_v2')])
  const failure=p.error||s.error||o.error
  if(failure) {setError(failure.code==='42P01'||failure.code==='PGRST205'?'Apply BrokerRelay_Billing_SQL_editor.sql before using billing.':failure.message);return}
  setPlans(p.data??[]);setSettings(s.data);setCompanies(o.data??[]);setError('')
 }
 useEffect(()=>{void(async()=>{const {data:a}=await supabase.auth.getUser();if(!a.user){window.location.href='/login';return}const {data:o}=await supabase.from('platform_admins').select('user_id').eq('user_id',a.user.id).maybeSingle();if(!o||a.user.email?.toLowerCase()!=='aruna@aidez.com.au'){window.location.href='/dashboard';return}setReady(true);await load();const requested=new URLSearchParams(window.location.search).get('company');if(requested)setCompany(requested)})()},[])
 async function savePlan(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');setNotice('');try{const included=Number(f.get('included'));if(!Number.isInteger(included)||included<0)throw new Error('Settlement allowance must be a whole number.');const {error:x}=await supabase.rpc('billing_save_plan',{p_key:String(f.get('key')).trim().toLowerCase(),p_name:String(f.get('name')),p_from:String(f.get('from')),p_monthly:cents(f.get('monthly')),p_included:included,p_extra:cents(f.get('extra'))});if(x)throw x;await load();setNotice('Future plan version saved. Current cycles and previous invoices retain their prices.');form.reset()}catch(x){setError(x instanceof Error?x.message:(x as {message?:string})?.message||'Could not save plan.')}finally{setBusy(false)}}
 async function saveSettings(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{const {error:x}=await supabase.rpc('billing_save_settings',{p_setup:cents(f.get('setup'),true),p_broker:cents(f.get('broker'),true),p_name:String(f.get('supplier')),p_abn:String(f.get('abn')),p_address:String(f.get('address')),p_payment:String(f.get('payment')),p_grace_days:Number(f.get('grace'))});if(x)throw x;await load();setNotice('Billing settings saved. One-time fees apply to future activations.')}catch(x){setError(x instanceof Error?x.message:(x as {message?:string})?.message||'Could not save settings.')}finally{setBusy(false)}}
 if(!ready)return <main className="page"><p>Checking Platform Owner access…</p></main>
 const current=new Map<string,BillingPlan>();for(const p of plans)if(p.effective_from<=monthStart()&&!current.has(p.plan_key))current.set(p.plan_key,p)
 return <main className="platformShell"><header className="platformHeader"><BrokerRelayBrand compact/><Link className="billingHeaderLink" href="/platform/companies">Platform companies</Link></header><div className="platformBody"><nav className="platformSidebar" aria-label="Platform navigation"><Link className="billingHeaderLink" href="/platform/companies">▦ Companies</Link><Link href="/platform/companies#invitations">✉ Invitations</Link><Link className="platformNavActive" aria-current="page" href="/platform/billing">▤ Billing &amp; plans</Link><Link href="/platform/operations">◉ Operations</Link><div className="platformSidebarBottom"><Link href="/dashboard">⌂ Broker Desk</Link></div></nav><div className="platformMain"><div className="platformHeading"><div><h1>Billing &amp; plans</h1><p className="muted">Configured prices exclude GST. New invoices add 10% GST to subscription, settlement and one-time fees. Enter your GST-registered supplier name and ABN before issuing tax invoices.</p><p>Configure company subscriptions, settlement allowances and invoice details. Amounts are in AUD.</p></div></div>
 {error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <button type="button" className="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');const r=await supabase.rpc('billing_run_maintenance');if(r.error)setError(r.error.message);else{setNotice(`Billing checked. ${r.data??0} invoice(s) generated.`);await load()}setBusy(false)}}>Run month-end and overdue checks</button>
 <div className="billingPlanGrid">{[...current.values()].map(p=><section className="card" key={p.id}><p className="eyebrow">MONTHLY PACKAGE</p><h2>{p.name}</h2><p><strong>{money(p.monthly_cents)}</strong> / month</p><p>{p.included_settlements} settlements included</p><p className="muted">{money(p.extra_cents)} per extra settlement</p></section>)}</div>
 <section className="card billingPanel"><h2>Company billing</h2><label>Select company<select value={company} onChange={e=>setCompany(e.target.value)}><option value="">Choose a company…</option>{companies.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label>{company&&<CompanyBillingPanel key={company} companyId={company} owner/>}</section>
 <BillingAutomationControls /><section className="card billingPanel"><h2>Schedule a package price or allowance</h2><p className="muted">Add a new version with the same package key to change future renewals. Use a new key for a new package. To revise a scheduled change, use the same key and future effective date. Current and past billed rates are preserved.</p><form className="billingForm" onSubmit={savePlan}><label>Package key<input name="key" placeholder="basic, professional or premium" required pattern="[a-z][a-z0-9_]{1,39}" list="billing-plan-keys"/></label><datalist id="billing-plan-keys">{[...current.keys()].map(k=><option key={k} value={k}/>)}</datalist><label>Display name<input name="name" required minLength={2} maxLength={80}/></label><label>Effective from<input name="from" type="date" defaultValue={monthStart(1)} min={monthStart(1)} required/></label><label>Monthly price ($, ex GST)<input name="monthly" type="number" min="0" step="0.01" required/></label><label>Included settlements<input name="included" type="number" min="0" step="1" required/></label><label>Each extra settlement ($, ex GST)<input name="extra" type="number" min="0" step="0.01" defaultValue="10" required/></label><button disabled={busy}>Save future package version</button></form>
 <details><summary>Package version history</summary><div className="tableWrap"><table><thead><tr><th>Package</th><th>Effective from</th><th>Monthly</th><th>Included</th><th>Extra</th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td>{p.name} ({p.plan_key})</td><td>{p.effective_from}</td><td>{money(p.monthly_cents)}</td><td>{p.included_settlements}</td><td>{money(p.extra_cents)}</td></tr>)}</tbody></table></div></details></section>
 {settings&&<section className="card billingPanel"><h2>One-time fees &amp; invoice details</h2><p className="muted">Leave a fee blank while undecided, or enter 0 to waive it. Setup includes the Head Broker. Existing staff are not charged retrospectively; reactivating the same broker does not create another activation fee.</p><form key={JSON.stringify(settings)} className="billingForm" onSubmit={saveSettings}><label>Overdue grace period (days)<input name="grace" type="number" min="0" max="90" step="1" required defaultValue={settings.grace_days}/></label><label>Company setup ($, ex GST)<input type="number" name="setup" min="0" step="0.01" defaultValue={settings.setup_cents===null?'':settings.setup_cents/100}/></label><label>Additional broker activation ($, ex GST)<input type="number" name="broker" min="0" step="0.01" defaultValue={settings.broker_cents===null?'':settings.broker_cents/100}/></label><label>Invoice supplier name<input name="supplier" required defaultValue={settings.supplier_name}/></label><label>Supplier ABN<input name="abn" defaultValue={settings.supplier_abn}/></label><label>Supplier address<textarea name="address" defaultValue={settings.supplier_address}/></label><label>Payment instructions<textarea name="payment" placeholder="Bank details and payment reference instructions" defaultValue={settings.payment_instructions}/></label><p className="muted">New invoices add 10% GST to the configured prices. Payment is recorded manually after funds are received; automatic collection requires a payment gateway.</p><button disabled={busy}>Save fees and invoice details</button></form></section>}
 </div></div></main>
}
